spring:
  application:
    name: employee-service
  mvc:
    servlet:
      path: /employee-service # this will be the url pattern
    pathmatch:
      matching-strategy: ant_path_matcher
server:
  port: 1111


eureka:
  instance:
    hostname: localhost
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8761/eureka